# Generated by Django 6.0.4 on 2026-04-27 02:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoEstadoCaballo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoEstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoEstadoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoEventoEquino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoParentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Caballo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('peso_max_soporta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sesiones_semanales_max', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('estado_salud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalogoestadocaballo')),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraEquina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('descripcion_veterinaria', models.TextField()),
                ('caballo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.caballo')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalogoeventoequino')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('caballo_favorito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.caballo')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalogoparentesco')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('caballo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.caballo')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalogoestadosesion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteSesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ansiedad_inicial', models.IntegerField(help_text='Escala del 1 al 10')),
                ('ansiedad_final', models.IntegerField(help_text='Escala del 1 al 10')),
                ('notas_clinicas', models.TextField()),
                ('recomendacion_casa', models.TextField()),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cedula_profesional', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalogoespecialidad')),
            ],
        ),
        migrations.AddField(
            model_name='sesion',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.terapeuta'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rol')),
            ],
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_limite', models.DateField()),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalogoestadopago')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sesion')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_tutor', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes_tutorados', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='PacienteDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalogodiagnostico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'diagnostico')},
            },
        ),
        migrations.CreateModel(
            name='ReporteObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalogoobjetivo')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportesesion')),
            ],
            options={
                'unique_together': {('reporte', 'objetivo')},
            },
        ),
    ]
