# Generated by Django 6.0.4 on 2026-04-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paciente_antecedentes_familiares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caballo',
            name='motivo_inactividad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
