# Generated by Django 6.0.4 on 2026-04-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_caballo_motivo_inactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tutor_secundario_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor_secundario_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
