# Generated by Django 6.0.4 on 2026-04-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_paciente_tutor_secundario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caballo',
            name='raza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caballo',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
