# Generated by Django 6.0.4 on 2026-04-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_caballo_raza_caballo_tipo_terapeuta_biografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='caballo',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
