# Generated by Django 6.0.4 on 2026-04-30 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_caballo_disponible_terapeuta_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='pagos/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='BitacoraSeguridad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('ARCHIVE', 'Registro Archivado'), ('RESTORE', 'Registro Restaurado'), ('CRITICAL_CONFIG', 'Cambio en Configuración Crítica')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario_accion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_realizados', to='api.usuario')),
                ('usuario_afectado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_recibidos', to='api.usuario')),
            ],
            options={
                'verbose_name_plural': 'Bitácora de Seguridad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
