# Generated by Django 6.0.4 on 2026-04-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pago_comprobante_pago_fecha_pago_bitacoraseguridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='caballo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
