# Generated by Django 6.0.4 on 2026-05-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_caballo_fecha_registro_paciente_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraequina',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bitacoraequina',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
