# Generated by Django 6.0.4 on 2026-05-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_bitacoraequina_fecha_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terapeuta',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='carrera',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='especialidad_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='terapeuta',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
