# Generated by Django 6.0.4 on 2026-05-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='archivada',
            field=models.BooleanField(default=False, help_text='Borrado lógico'),
        ),
    ]
