# Generated by Django 6.0.4 on 2026-05-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sesion_archivada'),
    ]

    operations = [
        migrations.AddField(
            model_name='caballo',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='caballos/'),
        ),
    ]
