# Generated by Django 6.0.4 on 2026-05-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_caballo_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duración de la sesión en minutos'),
        ),
    ]
